env:
  global:
  - TERM=dumb
  - secure: ICr0owjtW4RN8CdsHx3ctUliSNjgnmHWcAzA/Zhsg6SLY0gmT99kK0GKI4wrUji2ce2FOr9FxiXNVneGh5T+PTM0GjrYrYSfHCjJchGUSY9TgIUBM+02I2+80YR92iHZZeh6/ToeBvbsOZwQwGQRVLAplKsvWwT6BAIk/sDuuja1sd95qjuSg1M3YZ5+kahY/oixFfW+QvKnI8oza9U/gIIXV7J6AbL7sfpo5B0c/hRuZDcwAZM8gPyOhb+JmnT0QEcR3B+mgEhY4l49ZgGDgc2Q65Pv7fIzNlX6FKOqdDEoRw+8uxlu54OtK9tgngrJ6uW6u/csyBRcVKQt7bWF2zfeYYi4DuJiswU+7G0CcPcuvJeGHRf6XTnofa0pCSPcnFXFYJ+VYDbZWGp6TEzFBi88/+1tskDqnuU3HRP3qnqC4H+dO0FWiSQp+yOGt/kv/6onzYvWQgUCX8XdBhs+W0AarWN1gPCCS99HcZawJgdaMO4t+v0pV9g4zJsGRB2xHgkzcpfbzEOzOvEewocM2jPiUIrMKQ4FaAE05cHGoXNQkjx/rJjNAatT6hK4UYhD/TQGDydgIV8oCwBpVv+93/SGCq6NI0Fh6RZ5Bpt9w6/d42PcJDYgbCzVyen+wvTq5+nz6HQMIHD9sPCr5Ivg1HqKb5cB4pS1GbWRccDo9Ko=
language: java
jdk: oraclejdk10
node_js: lts/*
service:
- docker
addons:
  apt:
    update: true
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-stable
    - libappindicator1
    - fonts-liberation
    - bash
    - curl
    - libxml2-utils
    - docker-ce
install: true
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
#
- sudo add-apt-repository universe -y >/dev/null
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends
  tree jq python-pip curl bash sudo >/dev/null
#
- sudo pip install httpie >/dev/null 2>&1
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 3000 80 >/dev/null
#
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - >/dev/null
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends yarn >/dev/null
#
- java -version
- ./mvnw -v
- node -v
- yarn -v
script:
- export root=$(pwd)
- ./mvnw >/dev/null
#
- cd ${root}/01-getting-started
- yarn -i
- (yarn start || true) &
- wait_for 1234
- yarn test
- yarn debug
- stop_any 1234
- yarn predeploy
cache:
  yarn: true
  directories:
  - "$HOME/.m2"
before_deploy:
- cd ${root}/
- ./mvnw -Pdocs
- mkdir -p ./target/generated-docs
- cp -Rf ./target/generated-docs/index.html ./target/generated-docs/404.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages
notifications:
  email: false
